export class ApplicationDetail {
    constructor(
        public loanApplicationDetailId: number,
        public applicationId: number,
        public obligorName: string,
        public approvedTenor: number,
        public approvedRate: number,
        public approvedAmount: number,
        public approvedProductName: string,
        public statusId: number,
        public exchangeRate: number,
        public currencyCode: string,
        public proposedProductName: string,
        public proposedTenor: number,
        public proposedRate: number,
        public proposedAmount: number,
        public proposedProductId: number,
        public approvedProductId: number,
        public convertedApprovedAmount: number,
        public customerId: number,
        public terms: string,
        public schedule: string,
        public companyId: number,
        public companyName: string,
        public createdBy: number,
        public lastUpdatedBy: number,
        public dateTimeCreated: string, // date
        // public dateTimeUpdated: Date,
        // public deleted: number,
        // public deletedBy: number,
        // public dateTimeDeleted: Date,
        // public canModified: boolean,
        // public userBranchId: number,
        // public userIPAddress: string,
        // public applicationUrl: string,
        // public staffId: number,
    ) { }
}
